### ISSUE TITLE
err 101

### ISSUE THREAD

**Issue by pouria-niknamvazifeh-mscst** [winlinvip/SimpleDHT#21]
Hi! 
I'm using the default code with Arduino Uno and a DHT11 but keep getting error code 101. I couldn't figure out a way to fix it.

**Comment by t-w** [comment]
I had similar issues (https://github.com/t-w/SimpleDHT/issues/2, https://github.com/t-w/SimpleDHT/issues/3). If you haven't resolved this, you can try a version with my patch:
https://github.com/t-w/SimpleDHT/tree/mega2560_r3
or slightly different timing in one place on comm. init.:
https://github.com/t-w/SimpleDHT/tree/esp8266
(the second might work for more cases, since the error threshold is lower / the code is more tolerant).

If this works for you (and I will have such signals from others) I can open a merge request, to improve the mainline. For the moment the patched version is only very briefly tested.

**Comment by winlinvip** [comment]
Please file a MergeRequest.

**Comment by winlinvip** [comment]
Please test 1.0.9
